import type { Metadata } from "next";
import { geistSans, geistMono } from "@/styles/fonts";
import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-auto max-w-[1440px]`}
      >
        {children}
      </body>
    </html>
  );
}
